name : microservices-dev-jgm

services:
  # PostgreSQL para User Service
  postgres-user-dev:
    image: postgres:15-alpine
    container_name: postgres-user-dev
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  #  ports:
  #    - "5432:5432"
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-user-dev-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    profiles:
      - dev


  #  User Service Dev
  user-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service-jgm:1.0
    container_name: user-service-dev
    ports:
     - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user-dev:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-user-dev:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped
    profiles:
      - dev

  # User Service Local
  user-service-local:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service-jgm:1.0
    container_name: user-service-local
    ports:
     - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - microservice-network
    restart: unless-stopped
    profiles:
      - local



networks:
  microservice-network:
    driver: bridge

volumes:
  postgres-user-dev-data:
    driver: local